version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/Alicanto-Backend
permissions:
    - object: /home/ubuntu/Alicanto-Backend
      owner: ubuntu
      group: ubuntu
hooks:
    BeforeInstall:
        - location: scripts/clean_instance.sh
          timeout: 600
          runas: ubuntu
    AfterInstall:
        - location: scripts/instance_os_dependencies.sh
          timeout: 600
          runas: ubuntu
        - location: scripts/python_dependencies.sh
          timeout: 600
          runas: ubuntu
        - location: scripts/gunicorn.sh
          timeout: 600
          runas: ubuntu
        - location: scripts/nginx.sh
          timeout: 600
          runas: ubuntu
    ApplicationStop:
        - location: scripts/stop_app.sh
          timeout: 600
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start_app.sh
          timeout: 600
          runas: ubuntu
